"""τ²-format emitter: (spec, seed, tasks) -> tau2-compatible task bundle.

The bundle is the deterministic artifact: tasks.json (tau2 schema) + a
checks.py carrying the spec-derived verifier predicates (zero-LLM by
construction) + manifest.json binding spec hash, seed, and bundle hash.
"""
from __future__ import annotations

import json
from pathlib import Path

from .spec import DomainSpec, World, bundle_hash

# NOTE: the self-contained tau2 EnvironmentEvaluator module (matching their
# replay-gold contract) is the next iteration; checks.py is the v0 verifier.


def serialize_task(task: dict) -> dict:
    ctx = task["ctx"]
    users = task["initial_world"].get("users")

    def uname(uid: str) -> str:
        u = users.get(uid, {})
        return u.get("name", uid) if isinstance(u, dict) else uid

    inbox_lines = []
    for ev in task["inbox"]:
        if ev["type"] == "order":
            inbox_lines.append(
                f"Order {ev['order_id']} ({ev.get('status', '')}, placed "
                f"{ev.get('placed_hours_ago', '?')}h ago)"
            )
        elif ev["type"] == "offer":
            inbox_lines.append(
                f"Offer {ev['offer_id']} on listing {ev['listing_id']} from "
                f"{uname(ev['from'])}: ${ev['amount']}"
            )
        elif ev["type"] == "message":
            inbox_lines.append(
                f"Message {ev['message_id']} from {uname(ev['from'])}: \"{ev['text']}\""
            )
    known = "\n".join(inbox_lines) if inbox_lines else "No pending inbox items."
    return {
        "id": task["id"],
        "description": {
            "purpose": f"[{task['archetype']}] {task['goal_desc'](ctx)}",
            "relevant_policies": None,
            "notes": f"role={task['role']}",
        },
        "user_scenario": {
            "persona": None,
            "instructions": {
                "task_instructions": task["prompt"],
                "domain": "marketplace",
                "reason_for_call": "Alex needs your help with their marketplace activity.",
                "known_info": known,
                "unknown_info": None,
            },
        },
        "initial_state": None,  # runner injects the sampled world
        "evaluation_criteria": {
            "actions": [],
            "communicate_info": [],
            "nl_assertions": [],  # audit: zero-LLM verification, no NL judging
            "reward_basis": ["DB"],
        },
        "annotations": None,
    }


def emit(spec: DomainSpec, seed: int, tasks: list[dict], world: World,
         out_dir: str | Path) -> Path:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    tasks_json = [serialize_task(t) for t in tasks]
    (out / "tasks.json").write_text(
        json.dumps(tasks_json, indent=2, default=str)
    )

    checks = []
    ctx_map = []
    arch_map = []
    for t in tasks:
        checks.append(f'    "{t["id"]}": {json.dumps(t["goal_desc"](t["ctx"]))},')
        ctx_map.append(f'    "{t["id"]}": {json.dumps(t["ctx"], default=str)},')
        arch_map.append(f'    "{t["id"]}": {json.dumps(t["archetype"])},')
    (out / "checks.py").write_text(
        "'''Spec-derived verifier predicates (zero-LLM). Generated by BenchBrew.'''\n"
        "from domains.marketplace import MARKETPLACE as SPEC\n\n"
        "GOAL_DESC = {\n" + "\n".join(checks) + "\n}\n\n"
        "ARCHETYPE = {\n" + "\n".join(arch_map) + "\n}\n\n"
        "TASK_CTX = {\n" + "\n".join(ctx_map) + "\n}\n\n"
        "def check(task_id, world):\n"
        "    task = {'ctx': TASK_CTX[task_id],\n"
        "            'goal': SPEC.archetypes[ARCHETYPE[task_id]]['goal']}\n"
        "    from benchbrew.verifier import check as _check\n"
        "    return _check(task, world)\n"
    )

    manifest = {
        "domain": spec.name,
        "spec_version": spec.version,
        "spec_hash": spec.spec_hash(),
        "seed": seed,
        "n_tasks": len(tasks),
        "bundle_hash": bundle_hash(spec, seed, _stripped(tasks)),
        "world": json.loads(world.canonical()),
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2, default=str))
    return out


def _stripped(tasks: list[dict]) -> list[dict]:
    from .spec import canonical_tasks
    return canonical_tasks(tasks)
