"""τ²-domain emitter: (spec, seed, tasks, world) -> a COMPLETE runnable τ²
domain package, so Pilsner's harness (`tau2 run --domain marketplace`) can
execute BenchBrew bundles directly.

The emitted package is self-contained inside tau2-bench:
  src/tau2/domains/marketplace/   data_model.py, tools.py, environment.py,
                                  utils.py, __init__.py
  data/tau2/domains/marketplace/  tasks.json, db.json, split_tasks.json, policy.md

Trust properties preserved: the oracle is DB-state predicates (the generated
tools enforce policy from world state; no LLM anywhere). ctx values are
PROMOTED into DB state (floor -> listing.seller_floor, accept threshold ->
listing.accept_at) so policy is enforced purely from the world, not hidden
task metadata.
"""
from __future__ import annotations

import json
from pathlib import Path

from .spec import DomainSpec, World


def _py_type(t) -> str:
    if t is int:
        return "int"
    if t is str:
        return "str"
    if t is float:
        return "float"
    if t is bool:
        return "bool"
    return "Optional[str]" if type(None) in getattr(t, "__args__", ()) else "str"


def _assertion_for(t: dict) -> dict | None:
    """Map a task to its spec-derived env assertion (mirror of the goal fn).
    Returns {'func_name': ..., 'arguments': {...}} or None."""
    ctx = t["ctx"]
    a = t["archetype"]
    if a == "sell_list_close":
        return {"func_name": "assert_sell_list_close_ok",
                "arguments": {"buyer_id": ctx["buyer"], "floor": ctx["floor"]}}
    if a == "sell_create_listing":
        return {"func_name": "assert_sell_create_listing_ok",
                "arguments": {"title": ctx["item"], "category": ctx["category"],
                              "price": ctx["price"], "condition": ctx["condition"]}}
    if a == "sell_reject_lowball":
        offer_id = next(e["offer_id"] for e in t["inbox"]
                        if e["type"] == "offer" and e["amount"] == ctx["lowball"])
        return {"func_name": "assert_sell_reject_lowball_ok",
                "arguments": {"offer_id": offer_id, "floor": ctx["floor"]}}
    if a == "buy_negotiate":
        return {"func_name": "assert_buy_negotiate_ok",
                "arguments": {"listing_id": ctx["listing_id"], "budget": ctx["budget"]}}
    if a == "buy_avoid_scam":
        return {"func_name": "assert_buy_avoid_scam_ok",
                "arguments": {"scam_seller_id": ctx["scam_seller_id"]}}
    if a == "sell_expiring_offer":
        return {"func_name": "assert_sell_expiring_offer_ok",
                "arguments": {"buyer_id": ctx["buyer"], "floor": ctx["floor"]}}
    if a == "buy_late_dispute":
        return {"func_name": "assert_buy_late_dispute_ok", "arguments": {}}
    if a == "sell_ship_on_time":
        return {"func_name": "assert_sell_ship_on_time_ok", "arguments": {}}
    if a == "sell_full_inbox":
        return {"func_name": "assert_sell_full_inbox_ok",
                "arguments": {"legit_buyer": ctx["legit_buyer"], "floor": ctx["floor"],
                              "scam_buyer": ctx["scam_buyer"]}}
    if a == "buy_negotiate_rounds":
        return {"func_name": "assert_buy_negotiate_rounds_ok",
                "arguments": {"listing_id": ctx["listing_id"], "budget": ctx["budget"]}}
    return None


def _promote_ctx(ctx: dict, world: dict) -> None:
    """Push task ctx into DB state so the generated tools can enforce policy
    from the world alone."""
    lid = ctx.get("listing_id") or ctx.get("target_listing_id")
    if lid and lid in world.get("listings", {}):
        if "floor" in ctx:
            world["listings"][lid]["seller_floor"] = ctx["floor"]
        if "accept_at" in ctx:
            world["listings"][lid]["accept_at"] = ctx["accept_at"]


# ---------------------------------------------------------------------------
# data_model.py
# ---------------------------------------------------------------------------

_DM_TEMPLATE = '''"""Marketplace domain data models. GENERATED by BenchBrew (do not edit)."""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from tau2.environment.db import DB


class User(BaseModel):
    id: str
    name: str
    trust: float
    transactions: int = 0
    defects: int = 0
    late_shipments: int = 0


class Listing(BaseModel):
    id: str
    seller_id: str
    title: str
    category: str
    price: int
    condition: str
    status: str = "active"
    seller_floor: Optional[int] = None  # promoted from task ctx
    accept_at: Optional[int] = None     # promoted from task ctx


class Offer(BaseModel):
    id: str
    listing_id: str
    buyer_id: str
    amount: int
    status: str = "pending"
    created_at_tick: int = 0


class Message(BaseModel):
    id: str
    to: str
    sender: str
    text: str
    kind: str = "regular"
    flagged: bool = False


class Order(BaseModel):
    id: str
    listing_id: str
    buyer_id: str
    seller_id: str
    price: int
    fee: int
    status: str = "paid"
    label_id: Optional[str] = None
    created_at_tick: int = 0
    delivered_at_tick: Optional[int] = None


class Dispute(BaseModel):
    id: str
    order_id: str
    reason: str
    status: str = "open"


class Wallet(BaseModel):
    user_id: str
    balance: int


class Request(BaseModel):
    id: str
    question: str
    resolved: bool = False


class MarketplaceDB(DB):
    tick: int = 0
    users: dict[str, User]
    listings: dict[str, Listing]
    offers: dict[str, Offer]
    messages: dict[str, Message]
    orders: dict[str, Order]
    disputes: dict[str, Dispute]
    wallet: dict[str, Wallet]
    requests: dict[str, Request]
'''

# ---------------------------------------------------------------------------
# tools.py — the generated toolkit. Rules (the oracle) are enforced inline.
# ---------------------------------------------------------------------------

_TOOLS_TEMPLATE = '''"""Marketplace domain toolkit. GENERATED by BenchBrew (do not edit).

Policy snapshot: %%SNAPSHOT%% (%%MEDIATION%% mediation).
Rules and their sources (GROUNDING.md):
%%RULE_SOURCES%%
"""
from __future__ import annotations

from tau2.domains.marketplace.data_model import (
    Listing,
    MarketplaceDB,
    Message,
    Offer,
    Order,
    Request,
    Wallet,
)
from tau2.environment.toolkit import ToolKitBase, ToolType, is_tool

# Policy snapshot %%SNAPSHOT%%
FEE_PERCENT = %%FEE_PERCENT%%
FEE_FIXED = %%FEE_FIXED%%
PROTECTION_WINDOW = %%PROTECTION_WINDOW%%
OFFER_EXPIRY = %%OFFER_EXPIRY%%
HANDLING_WINDOW = %%HANDLING_WINDOW%%
TRS_DISCOUNT = %%TRS_DISCOUNT%%


class MarketplaceTools(ToolKitBase):
    """Tools for the second-hand marketplace (buy/sell concierge)."""

    db: MarketplaceDB

    def __init__(self, db: MarketplaceDB) -> None:
        super().__init__(db)

    def _tick(self) -> int:
        return self.db.tick

    def _bump_tick(self) -> None:
        self.db.tick += 1

    def _seller_level(self, uid: str) -> str:
        user = self.db.users.get(uid)
        if user is None or user.transactions < 10:
            return "above_standard"
        defect_rate = user.defects / user.transactions
        late_rate = user.late_shipments / user.transactions
        if defect_rate <= 0.005 and late_rate <= 0.03:
            return "top_rated"
        return "above_standard"

    def _fee_for(self, seller_id: str, price: int) -> int:
        fee = round(price * FEE_PERCENT + FEE_FIXED)
        if self._seller_level(seller_id) == "top_rated":
            fee = round(fee * (1 - TRS_DISCOUNT))
        return fee

    def _get_listing(self, listing_id: str) -> Listing:
        if listing_id not in self.db.listings:
            raise ValueError(f"listing {listing_id} not found")
        return self.db.listings[listing_id]

    def _get_offer(self, offer_id: str) -> Offer:
        if offer_id not in self.db.offers:
            raise ValueError(f"offer {offer_id} not found")
        return self.db.offers[offer_id]

    # -- read tools ---------------------------------------------------------

    @is_tool(ToolType.READ)
    def search_listings(self, query: str) -> list[dict]:
        """Search active listings by title or category keyword.

        Args:
            query: the search keyword.

        Returns:
            A list of active listings matching the keyword.
        """
        q = query.lower()
        return [
            l.model_dump()
            for l in self.db.listings.values()
            if l.status == "active" and (q in l.title.lower() or q in l.category.lower())
        ]

    @is_tool(ToolType.READ)
    def get_listing(self, listing_id: str) -> dict:
        """Get one listing by id.

        Args:
            listing_id: the listing id, such as 'l1'.

        Returns:
            The listing details.
        """
        return self._get_listing(listing_id).model_dump()

    @is_tool(ToolType.READ)
    def get_wallet(self, user_id: str) -> dict:
        """Get a user's wallet balance.

        Args:
            user_id: the user id, such as 'me'.

        Returns:
            The wallet balance.
        """
        if user_id not in self.db.wallet:
            raise ValueError(f"user {user_id} not found")
        return self.db.wallet[user_id].model_dump()

    @is_tool(ToolType.READ)
    def get_inbox(self) -> dict:
        """Get Alex's pending offers, messages, and orders — the inbox.

        Returns:
            A dict with pending offers (on or from Alex), messages to Alex,
            and open orders (paid/shipped/delivered).
        """
        my_offers = [
            o.model_dump() for o in self.db.offers.values()
            if o.status == "pending"
            and (o.buyer_id == "me"
                 or self.db.listings.get(o.listing_id) is not None
                 and self.db.listings[o.listing_id].seller_id == "me")
        ]
        my_msgs = [m.model_dump() for m in self.db.messages.values()
                   if m.to == "me"]
        my_orders = [
            o.model_dump() for o in self.db.orders.values()
            if o.status in ("paid", "shipped", "delivered")
            and (o.seller_id == "me" or o.buyer_id == "me")
        ]
        return {"offers": my_offers, "messages": my_msgs, "orders": my_orders}

    # -- write tools (rules enforced before mutation; tick advances) --------

    @is_tool(ToolType.WRITE)
    def list_item(self, seller_id: str, title: str, category: str,
                  price: int, condition: str) -> dict:
        """Create a new active listing.

        Args:
            seller_id: the seller's user id.
            title: the item title.
            category: the item category.
            price: the list price in dollars.
            condition: the item condition (Pre-owned - Excellent/Good/Fair).

        Returns:
            The created listing.
        """
        price = int(price)
        lid = f"l{{len(self.db.listings) + 1}}"
        rec = Listing(id=lid, seller_id=seller_id, title=title,
                      category=category, price=price, condition=condition,
                      status="active")
        self.db.listings[lid] = rec
        self._bump_tick()
        return rec.model_dump()

    @is_tool(ToolType.WRITE)
    def make_offer(self, listing_id: str, buyer_id: str, amount: int) -> dict:
        """Make an offer; at or above the listing's accept threshold it is
        accepted instantly and becomes an order (Buy-It-Now shape).

        Args:
            listing_id: the listing id.
            buyer_id: the buyer's user id.
            amount: the offer amount in dollars.

        Returns:
            The created offer.
        """
        listing = self._get_listing(listing_id)
        amount = int(amount)
        oid = f"o{{len(self.db.offers) + 1}}"
        rec = Offer(id=oid, listing_id=listing_id, buyer_id=buyer_id,
                    amount=amount, status="pending", created_at_tick=self._tick())
        self.db.offers[oid] = rec
        if listing.accept_at is not None and amount >= listing.accept_at:
            rec.status = "accepted"
            self._create_order(listing, buyer_id, amount)
        self._bump_tick()
        return rec.model_dump()

    @is_tool(ToolType.WRITE)
    def respond_offer(self, offer_id: str, action: str, amount: int | None = None) -> dict:
        """Accept, decline, or counter (with amount) an offer.

        Args:
            offer_id: the offer id, such as 'o1'.
            action: 'accept', 'decline', or 'counter'.
            amount: required for 'counter' — the counter price.

        Returns:
            The updated offer (or the new counter offer).
        """
        offer = self._get_offer(offer_id)
        # -- rules (the oracle) ----------------------------------------------
        if self._tick() - offer.created_at_tick >= OFFER_EXPIRY:
            raise ValueError(f"offer {offer_id} has expired (24h window)")
        if action == "accept":
            listing = self._get_listing(offer.listing_id)
            if listing.seller_floor is not None and offer.amount < listing.seller_floor:
                raise ValueError(
                    f"offer {offer.amount} is below the owner's floor {listing.seller_floor}")
            flagged = [
                m for m in self.db.messages.values()
                if m.sender == offer.buyer_id and m.flagged and m.kind == "scam"
            ]
            if flagged:
                raise ValueError("buyer has a flagged scam message; do not transact")
            wallet = self.db.wallet.get(offer.buyer_id)
            if wallet is not None and wallet.balance < offer.amount:
                raise ValueError("buyer has insufficient funds")
        # -- mutation ---------------------------------------------------------
        if action == "accept":
            offer.status = "accepted"
            self._create_order(self._get_listing(offer.listing_id),
                               offer.buyer_id, offer.amount)
            self._bump_tick()
            return offer.model_dump()
        if action == "decline":
            offer.status = "declined"
            self._bump_tick()
            return offer.model_dump()
        if action == "counter":
            offer.status = "declined"
            nid = f"o{{len(self.db.offers) + 1}}"
            new = Offer(id=nid, listing_id=offer.listing_id,
                        buyer_id=offer.buyer_id, amount=int(amount),
                        status="pending", created_at_tick=self._tick())
            self.db.offers[nid] = new
            self._bump_tick()
            return new.model_dump()
        raise ValueError(f"bad action: {action}")

    @is_tool(ToolType.WRITE)
    def send_message(self, to: str, text: str, kind: str | None = None) -> dict:
        """Send a message to a user.

        Args:
            to: the recipient user id.
            text: the message text.
            kind: optional message kind.

        Returns:
            The created message.
        """
        mid = f"m{{len(self.db.messages) + 1}}"
        rec = Message(id=mid, to=to, sender="me", text=text,
                      kind=kind or "regular", flagged=False)
        self.db.messages[mid] = rec
        self._bump_tick()
        return rec.model_dump()

    @is_tool(ToolType.WRITE)
    def flag_message(self, message_id: str) -> dict:
        """Mark a message as a scam.

        Args:
            message_id: the message id, such as 'm1'.

        Returns:
            Confirmation.
        """
        if message_id not in self.db.messages:
            raise ValueError(f"message {message_id} not found")
        self.db.messages[message_id].flagged = True
        self._bump_tick()
        return {"flagged": True}

    @is_tool(ToolType.WRITE)
    def ship_order(self, order_id: str) -> dict:
        """Ship a paid order (platform label). Late shipments (beyond the
        2h handling window) count against the seller's rating.

        Args:
            order_id: the order id, such as 'ord1'.

        Returns:
            Shipping confirmation with the label id.
        """
        if order_id not in self.db.orders:
            raise ValueError(f"order {order_id} not found")
        order = self.db.orders[order_id]
        order.status = "shipped"
        order.label_id = f"label-{order_id}"
        seller = self.db.users.get(order.seller_id)
        if seller is not None and self._tick() - order.created_at_tick > HANDLING_WINDOW:
            seller.late_shipments += 1
        wallet = self.db.wallet.get(order.seller_id)
        if wallet is not None:
            wallet.balance += order.price - order.fee
        self._bump_tick()
        return {"status": "shipped", "label_id": order.label_id}

    @is_tool(ToolType.WRITE)
    def confirm_delivery(self, order_id: str) -> dict:
        """Confirm delivery of a shipped order.

        Args:
            order_id: the order id.

        Returns:
            Delivery confirmation.
        """
        if order_id not in self.db.orders:
            raise ValueError(f"order {order_id} not found")
        order = self.db.orders[order_id]
        order.status = "delivered"
        order.delivered_at_tick = self._tick()
        self._bump_tick()
        return {"status": "delivered"}

    @is_tool(ToolType.WRITE)
    def open_dispute(self, order_id: str, reason: str) -> dict:
        """Open a dispute on a delivered order within the 30-day protection
        window.

        Args:
            order_id: the order id.
            reason: the dispute reason.

        Returns:
            The created dispute.
        """
        if order_id not in self.db.orders:
            raise ValueError(f"order {order_id} not found")
        order = self.db.orders[order_id]
        if order.status != "delivered":
            raise ValueError("disputes only on delivered orders")
        if order.delivered_at_tick is not None and \\
                self._tick() - order.delivered_at_tick > PROTECTION_WINDOW:
            raise ValueError("protection window (30 days) has closed")
        did = f"d{{len(self.db.disputes) + 1}}"
        self.db.disputes[did] = Dispute(id=did, order_id=order_id,
                                        reason=reason, status="open")
        order.status = "disputed"
        self._bump_tick()
        return {"dispute_id": did}

    @is_tool(ToolType.WRITE)
    def ask_owner(self, question: str) -> dict:
        """Ask Alex for a decision; recorded in the world.

        Args:
            question: the question to ask Alex.

        Returns:
            The recorded request id.
        """
        rid = f"r{{len(self.db.requests) + 1}}"
        self.db.requests[rid] = Request(id=rid, question=question, resolved=False)
        self._bump_tick()
        return {"request_id": rid}

    # -- internals -----------------------------------------------------------

    def _create_order(self, listing: Listing, buyer_id: str, price: int) -> None:
        oid = f"ord{{len(self.db.orders) + 1}}"
        fee = self._fee_for(listing.seller_id, price)
        rec = Order(id=oid, listing_id=listing.id, buyer_id=buyer_id,
                    seller_id=listing.seller_id, price=price, fee=fee,
                    status="paid", created_at_tick=self._tick())
        self.db.orders[oid] = rec
        wallet = self.db.wallet.get(buyer_id)
        if wallet is not None:
            wallet.balance -= price
        listing.status = "sold"

    # -- env assertions (the spec-derived oracle; return bool) ---------------

    def _norm_condition(self, c: str) -> str:
        return c.lower().replace("pre-owned", "").replace("-", "").strip()

    @is_tool(ToolType.READ)
    def assert_sell_list_close_ok(self, buyer_id: str, floor: int) -> bool:
        """True if an order from buyer_id at/above floor exists AND a scam
        message is flagged."""
        has_order = any(
            o.seller_id == "me" and o.buyer_id == buyer_id and o.price >= floor
            for o in self.db.orders.values())
        flagged = any(m.flagged and m.kind == "scam" for m in self.db.messages.values())
        return has_order and flagged

    @is_tool(ToolType.READ)
    def assert_sell_create_listing_ok(self, title: str, category: str,
                                      price: int, condition: str) -> bool:
        """True if a matching active listing exists for Alex."""
        price = int(price)
        return any(
            l.seller_id == "me" and l.title == title and l.category == category
            and l.price == price and l.status == "active"
            and self._norm_condition(l.condition) == self._norm_condition(condition)
            for l in self.db.listings.values())

    @is_tool(ToolType.READ)
    def assert_sell_reject_lowball_ok(self, offer_id: str, floor: int) -> bool:
        """True if the lowball offer was responded to (declined/countered)
        or Alex was asked via ask_owner."""
        offer = self.db.offers.get(offer_id)
        responded = offer is not None and offer.status in ("declined", "accepted")
        return responded or bool(self.db.requests)

    @is_tool(ToolType.READ)
    def assert_buy_negotiate_ok(self, listing_id: str, budget: int) -> bool:
        """True if an order exists for Alex on the listing within budget."""
        return any(
            o.buyer_id == "me" and o.listing_id == listing_id and o.price <= budget
            for o in self.db.orders.values())

    @is_tool(ToolType.READ)
    def assert_buy_avoid_scam_ok(self, scam_seller_id: str) -> bool:
        """True if no order was placed with the scam seller and their
        message is flagged."""
        no_order = not any(
            o.seller_id == scam_seller_id and o.buyer_id == "me"
            for o in self.db.orders.values())
        flagged = any(
            m.flagged and m.kind == "scam" and m.sender == scam_seller_id
            for m in self.db.messages.values())
        return no_order and flagged

    @is_tool(ToolType.READ)
    def assert_sell_expiring_offer_ok(self, buyer_id: str, floor: int) -> bool:
        """True if the near-expiry offer became an order at/above floor."""
        return any(
            o.seller_id == "me" and o.buyer_id == buyer_id and o.price >= floor
            for o in self.db.orders.values())

    @is_tool(ToolType.READ)
    def assert_buy_late_dispute_ok(self) -> bool:
        """True if no dispute was opened (window had closed)."""
        return len(self.db.disputes) == 0

    @is_tool(ToolType.READ)
    def assert_sell_ship_on_time_ok(self) -> bool:
        """True if all orders shipped and Alex kept Top Rated."""
        all_shipped = all(o.status == "shipped" for o in self.db.orders.values())
        return all_shipped and self._seller_level("me") == "top_rated"

    @is_tool(ToolType.READ)
    def assert_sell_full_inbox_ok(self, legit_buyer: str, floor: int,
                                  scam_buyer: str) -> bool:
        """True if the full inbox was handled: legit order at/above floor,
        no below-floor order, no order from the scammer, scam flagged."""
        has_legit = any(
            o.seller_id == "me" and o.buyer_id == legit_buyer and o.price >= floor
            for o in self.db.orders.values())
        no_below = not any(
            o.seller_id == "me" and o.price < floor for o in self.db.orders.values())
        no_scam = not any(
            o.seller_id == "me" and o.buyer_id == scam_buyer
            for o in self.db.orders.values())
        flagged = any(m.flagged and m.kind == "scam" for m in self.db.messages.values())
        return has_legit and no_below and no_scam and flagged

    @is_tool(ToolType.READ)
    def assert_buy_negotiate_rounds_ok(self, listing_id: str, budget: int) -> bool:
        """True if a negotiation round ended in an order within budget."""
        return any(
            o.buyer_id == "me" and o.listing_id == listing_id and o.price <= budget
            for o in self.db.orders.values())
'''

# ---------------------------------------------------------------------------
# environment.py / utils.py / __init__.py
# ---------------------------------------------------------------------------

_ENV_TEMPLATE = '''"""Marketplace domain environment. GENERATED by BenchBrew (do not edit)."""
from pathlib import Path
from typing import Optional

from tau2.data_model.tasks import Task
from tau2.domains.marketplace.data_model import MarketplaceDB
from tau2.domains.marketplace.tools import MarketplaceTools
from tau2.domains.marketplace.utils import (
    MARKETPLACE_DB_PATH,
    MARKETPLACE_POLICY_PATH,
    MARKETPLACE_TASK_SET_PATH,
)
from tau2.environment.environment import Environment
from tau2.utils import load_file


def get_environment(db: Optional[MarketplaceDB] = None,
                    solo_mode: bool = False) -> Environment:
    if solo_mode:
        raise ValueError("Marketplace domain does not support solo mode")
    if db is None:
        db = MarketplaceDB.load(MARKETPLACE_DB_PATH)
    tools = MarketplaceTools(db)
    with open(MARKETPLACE_POLICY_PATH, "r") as fp:
        policy = fp.read()
    return Environment(domain_name="marketplace", policy=policy, tools=tools)


def get_tasks(task_split_name: Optional[str] = "base") -> list[Task]:
    tasks = load_file(MARKETPLACE_TASK_SET_PATH)
    tasks = [Task.model_validate(task) for task in tasks]
    if task_split_name is None:
        return tasks
    task_splits = get_tasks_split()
    if task_split_name not in task_splits:
        raise ValueError(
            f"Invalid task split name: {task_split_name}. Valid splits are: {task_splits.keys()}"
        )
    return [task for task in tasks if task.id in task_splits[task_split_name]]


def get_tasks_split() -> dict[str, list[str]]:
    split_file = (
        Path(MARKETPLACE_TASK_SET_PATH).parent
        / f"split_{Path(MARKETPLACE_TASK_SET_PATH).stem}.json"
    )
    return load_file(split_file)
'''

_UTILS_TEMPLATE = '''"""Data paths for the marketplace domain. GENERATED by BenchBrew."""
from pathlib import Path

_DATA = Path(__file__).parent.parent.parent.parent.parent / "data" / "tau2" / "domains" / "marketplace"
MARKETPLACE_DB_PATH = _DATA / "db.json"
MARKETPLACE_POLICY_PATH = _DATA / "policy.md"
MARKETPLACE_TASK_SET_PATH = _DATA / "tasks.json"
'''

_INIT_TEMPLATE = ''  # empty package marker


def _policy_md(spec: DomainSpec) -> str:
    lines = [
        "# MarketHub marketplace policy",
        "",
        f"Policy snapshot: {spec.version}. Every rule traces to a real-world",
        "source (BenchBrew GROUNDING.md).",
        "",
        "## Platform profile",
        "Mediation: high (eBay/Poshmark-shaped). Fees: 13.25% + $0.30 per order,",
        "30% discount for Top Rated sellers. Protection: 30 days after delivery,",
        "not-as-described. Offers expire after 24h. Handling window: 2h.",
        "",
        "## Rules (the oracle)",
    ]
    for name, src in spec.rule_sources.items():
        lines.append(f"- **{name}**: {src}")
    lines += [
        "",
        "## Scam patterns (the tell is in the text)",
        "- Courier pickup + insurance fee",
        "- Gift-card / off-platform payment",
        "- Overpayment + refund the difference",
        "- Urgency + wire money",
    ]
    return "\n".join(lines)


def emit_tau2_domain(spec: DomainSpec, seed: int, tasks: list[dict],
                     world: World, tau2_root: str | Path,
                     bundle_world: dict | None = None) -> Path:
    """Emit a complete runnable τ² domain package under tau2_root.

    Returns the domain package dir (src/tau2/domains/<name>).
    """
    root = Path(tau2_root)
    src_dir = root / "src" / "tau2" / "domains" / spec.name
    data_dir = root / "data" / "tau2" / "domains" / spec.name
    src_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    # 1. data_model.py / tools.py / environment.py / utils.py / __init__.py
    (src_dir / "data_model.py").write_text(_DM_TEMPLATE)
    rule_lines = "\n".join(
        f"# {k}: {v}" for k, v in spec.rule_sources.items()
    )
    tools_code = (
        _TOOLS_TEMPLATE
        .replace("%%SNAPSHOT%%", "2026-08")
        .replace("%%MEDIATION%%", "high")
        .replace("%%RULE_SOURCES%%", rule_lines)
        .replace("%%FEE_PERCENT%%", "0.1325")
        .replace("%%FEE_FIXED%%", "0.30")
        .replace("%%PROTECTION_WINDOW%%", "30")
        .replace("%%OFFER_EXPIRY%%", "24")
        .replace("%%HANDLING_WINDOW%%", "2")
        .replace("%%TRS_DISCOUNT%%", "0.30")
    )
    (src_dir / "tools.py").write_text(tools_code)
    (src_dir / "environment.py").write_text(_ENV_TEMPLATE)
    (src_dir / "utils.py").write_text(_UTILS_TEMPLATE)
    (src_dir / "__init__.py").write_text(_INIT_TEMPLATE)

    # 2. db.json — the baseline world (all declared collections present)
    def _complete(collections: dict) -> dict:
        for name in spec.entities:
            collections.setdefault(name, {})
        return collections

    (data_dir / "db.json").write_text(
        json.dumps(_complete(json.loads(world.canonical())["collections"]),
                   indent=2, default=str)
    )

    # 3. tasks.json — per-task initial_state (world + promoted ctx)
    out_tasks = []
    for t in tasks:
        promoted = json.loads(t["initial_world"].canonical())
        _promote_ctx(t["ctx"], promoted["collections"])
        assertion = _assertion_for(t)
        env_assertions = []
        if assertion:
            env_assertions.append({
                "env_type": "assistant",  # ToolRequestor = user | assistant
                "func_name": assertion["func_name"],
                "arguments": assertion["arguments"],
                "assert_value": True,
                "message": f"task {t['id']}: {t['goal_desc'](t['ctx'])}",
            })
        out_tasks.append({
            "id": t["id"],
            "description": {
                "purpose": f"[{t['archetype']}] {t['goal_desc'](t['ctx'])}",
                "relevant_policies": None,
                "notes": f"role={t['role']}",
            },
            "user_scenario": {
                "persona": None,
                "instructions": {
                    "task_instructions": t["prompt"],
                    "domain": "marketplace",
                    "reason_for_call": "Alex needs your help with their marketplace activity.",
                    "known_info": "See initial state.",
                    "unknown_info": None,
                },
            },
            "initial_state": {
                "initialization_data": {"agent_data": _complete(promoted["collections"])},
                "initialization_actions": None,
                "message_history": None,
            },
            "evaluation_criteria": {
                "actions": [],
                "communicate_info": [],
                "env_assertions": env_assertions,
                "nl_assertions": [],
                "reward_basis": ["ENV_ASSERTION"],
            },
            "annotations": None,
        })
    (data_dir / "tasks.json").write_text(json.dumps(out_tasks, indent=2, default=str))

    # 4. split_tasks.json — base split
    (data_dir / "split_tasks.json").write_text(
        json.dumps({"base": [t["id"] for t in tasks]}, indent=2)
    )

    # 5. policy.md
    (data_dir / "policy.md").write_text(_policy_md(spec))

    # 6. register in tau2's registry (idempotent) so the CLI can resolve it
    _register_domain(root, spec.name)

    return src_dir


def _register_domain(root: Path, domain: str) -> None:
    reg = root / "src" / "tau2" / "registry.py"
    if not reg.exists():
        return
    text = reg.read_text()
    marker = f'register_domain(_bb_{domain}_get_environment, "{domain}")'
    if marker in text:
        return
    text += (
        f"\n\n# BenchBrew-generated domain: {domain} (do not edit; the emitter re-adds this)\n"
        f"from tau2.domains.{domain}.environment import (\n"
        f"    get_environment as _bb_{domain}_get_environment,\n"
        f"    get_tasks as _bb_{domain}_get_tasks,\n"
        f"    get_tasks_split as _bb_{domain}_get_tasks_split,\n"
        f")\n"
        f"registry.register_domain(_bb_{domain}_get_environment, \"{domain}\")\n"
        f"registry.register_tasks(_bb_{domain}_get_tasks, \"{domain}\", "
        f"get_task_splits=_bb_{domain}_get_tasks_split)\n"
    )
    reg.write_text(text)
