"""τ²-domain emitter: (spec, seed, tasks, world) -> a COMPLETE runnable τ²
domain package, so Pilsner's harness (`tau2 run --domain <name>`) can execute
ANY BenchBrew bundle directly.

The emitted package is self-contained inside tau2-bench:
  src/tau2/domains/<name>/   data_model.py, tools.py, environment.py,
                             utils.py, spec_code.py, compat.py, __init__.py
  data/tau2/domains/<name>/  tasks.json, db.json, split_tasks.json, policy.md

GENERIC by construction: the domain's own module source is embedded
(spec_code.py + a compat shim for the benchbrew.spec names it imports) and
the τ² adapter is generated from the spec metadata:
  - data_model.py  <- EntitySpec fields -> pydantic models + a DB whose
                      `collections: dict[str, dict[str, dict]]` stores raw
                      dicts so the spec's in-place world mutations persist
  - tools.py       <- ToolSpec params -> @is_tool signatures; bodies run the
                      spec's OWN rules + impls against a dict-interface view
                      of the DB (the oracle is the spec's rule set, not a
                      re-translation)
  - environment.py <- tasks.json + per-task env_assertions whose tools call
                      the spec's OWN goal functions
  - ctx promotion  <- each task's ctx is embedded as a synthetic `_ctx`
                      collection in that task's world, so policy AND goals
                      read task parameters from world state (the marketplace
                      "floor -> listing.seller_floor" pattern, generalized)

Trust properties preserved: zero LLM anywhere; the oracle is DB-state
predicates from the spec itself; determinism comes from (spec, seed).
"""

from __future__ import annotations

import importlib
import inspect
import json
import re
from pathlib import Path

from .spec import DomainSpec, World

_IMPORT_RE = re.compile(r"^from benchbrew\.spec import .*$", re.M)


def _py_type(t) -> str:
    if t is int:
        return "int"
    if t is str:
        return "str"
    if t is float:
        return "float"
    if t is bool:
        return "bool"
    if type(None) in getattr(t, "__args__", ()):
        return f"Optional[{_py_type(next(a for a in t.__args__ if a is not type(None)))}]"
    if t is list:
        return "list"
    if getattr(t, "__origin__", None) is list:
        return f"list[{_py_type(t.__args__[0])}]"
    return "str"


def _spec_source(spec: DomainSpec) -> str:
    """Return the domain module's source with the benchbrew.spec import
    rewritten to the emitted compat shim."""
    first_goal = next(iter(spec.archetypes.values()))["goal"]
    mod = importlib.import_module(first_goal.__module__)
    src = inspect.getsource(mod)
    src = _IMPORT_RE.sub("from .compat import DomainSpec, EntitySpec, "
                         "PolicyError, ToolSpec, World", src)
    return src


def _goal_fn_names(spec: DomainSpec) -> dict[str, str]:
    out = {}
    for name, arch in spec.archetypes.items():
        out[name] = arch["goal"].__name__
    return out


def _rule_names(spec: DomainSpec) -> dict[str, str]:
    return {name: fn.__name__ for name, fn in spec.rules.items()}


def _impl_names(spec: DomainSpec) -> dict[str, str]:
    return {name: fn.__name__ for name, fn in spec.tool_impls.items()}


def _tool_param_lines(spec: DomainSpec, tool: str) -> tuple[str, str]:
    """Generate the method signature params and the args dict for a tool."""
    params = spec.tools[tool].params
    sig, args = [], []
    for pname, ptype in params.items():
        t = _py_type(ptype)
        if type(None) in getattr(ptype, "__args__", ()):
            sig.append(f"{pname}: {t} = None")
        else:
            sig.append(f"{pname}: {t}")
        args.append(f'"{pname}": {pname}')
    return ", ".join(sig), ", ".join(args)


# ---------------------------------------------------------------------------
# Generated package files
# ---------------------------------------------------------------------------

_COMPAT_TEMPLATE = '''"""Compatibility shim so the embedded spec module imports standalone.
GENERATED by BenchBrew (do not edit)."""

from __future__ import annotations


class PolicyError(Exception):
    """A policy violation — the oracle's verdict on a tool call."""


class World:
    """Minimal dict-interface world matching benchbrew.spec.World."""

    def __init__(self) -> None:
        self._collections: dict = {}
        self.tick: int = 0

    def get(self, name: str) -> dict:
        return self._collections.setdefault(name, {})

    def setdefault(self, name: str, val=None) -> dict:
        return self._collections.setdefault(name, {} if val is None else val)

    def clone(self):
        import copy
        return copy.deepcopy(self)


class EntitySpec:
    def __init__(self, *args, **kwargs) -> None:
        pass


class ToolSpec:
    def __init__(self, *args, **kwargs) -> None:
        pass


class DomainSpec:
    def __init__(self, *args, **kwargs) -> None:
        pass
'''


def _gen_data_model(spec: DomainSpec) -> str:
    cap = spec.name.replace("_", " ").title().replace(" ", "")
    lines = [
        f'"""{cap} domain data models. GENERATED by BenchBrew (do not edit)."""',
        "from __future__ import annotations",
        "",
        "from typing import Any, Optional",
        "",
        "from pydantic import BaseModel",
        "",
        "from tau2.environment.db import DB",
        "",
    ]
    for coll, ent in spec.entities.items():
        model = coll.title().replace("_", "")
        lines.append(f"class {model}(BaseModel):")
        if not ent.fields:
            lines.append("    pass")
            lines.append("")
            continue
        for fname, ftype in ent.fields.items():
            default = ""
            if type(None) in getattr(ftype, "__args__", ()):
                default = " = None"
            lines.append(f"    {fname}: {_py_type(ftype)}{default}")
        lines.append("")
    lines += [
        f"class {cap}DB(DB):",
        "    tick: int = 0",
        "    # task parameters (promoted ctx) — the oracle reads task state",
        "    # from the world, never from hidden metadata",
        "    task_ctx: dict[str, Any] = {}",
    ]
    for coll in spec.entities:
        lines.append(f"    {coll}: dict[str, dict] = {{}}")
    lines.append("")
    return "\n".join(lines)


def _gen_tools(spec: DomainSpec) -> str:
    cap = spec.name.replace("_", " ").title().replace(" ", "")
    plat = getattr(spec, "platform", None) or {}
    rule_lines = "\n".join(f"# {k}: {v}" for k, v in spec.rule_sources.items())
    lines = [
        f'"""{cap} domain toolkit. GENERATED by BenchBrew (do not edit).',
        "",
        f"Policy snapshot: {plat.get('snapshot', 'see policy.md')} "
        f"({plat.get('mediation', '?')} mediation).",
        "Rules (the oracle) and their sources:",
        rule_lines,
        '"""',
        "from __future__ import annotations",
        "",
        "from tau2.environment.toolkit import ToolKitBase, ToolType, is_tool",
        "",
        f"from .data_model import {cap}DB",
        "from .spec_code import (",
    ]
    imports = []
    for name, fn in _rule_names(spec).items():
        imports.append(f"    {fn} as _rule_{name},")
    for name, fn in _impl_names(spec).items():
        imports.append(f"    {fn} as _impl_{name},")
    for arch, fn in _goal_fn_names(spec).items():
        imports.append(f"    {fn} as _goal_{arch},")
    lines += imports + [")", "", "", "class _View:", "    \"\"\"Dict-interface world view over the DB (matches benchbrew World).\"\"\"",
        "",
        "    def __init__(self, db) -> None:",
        "        self.db = db",
        "",
        "    @property",
        "    def tick(self) -> int:",
        "        return self.db.tick",
        "",
        "    def get(self, name: str) -> dict:",
        '        if name == "_ctx":',
        "            return self.db.task_ctx",
        "        if not hasattr(self.db, name):",
        "            setattr(self.db, name, {})",
        "        return getattr(self.db, name)",
        "",
        "    def setdefault(self, name: str, val=None) -> dict:",
        '        return self.get(name) if val is None else val',
        "",
        "",
        f"class {cap}Tools(ToolKitBase):",
        f'    """Tools for the {spec.name} domain."""',
        "",
        f"    db: {cap}DB",
        "",
        f"    def __init__(self, db: {cap}DB) -> None:",
        "        super().__init__(db)",
        "",
        "    _RULES = [",
    ]
    for name in spec.rules:
        lines.append(f"        _rule_{name},")
    lines += [
        "    ]",
        "",
        "    _IMPLS = {",
    ]
    for name in spec.tool_impls:
        lines.append(f'        "{name}": _impl_{name},')
    lines += [
        "    }",
        "",
        "    _WRITES = {",
    ]
    for name, ts in spec.tools.items():
        if ts.kind == "write":
            lines.append(f'        "{name}",')
    lines += [
        "    }",
        "",
        "    def _run(self, name: str, args: dict) -> dict:",
        "        view = _View(self.db)",
        '        ctx = view.get("_ctx")',
        "        for rule in self._RULES:",
        "            rule(view, name, args, ctx)",
        "        out = self._IMPLS[name](view, args, ctx)",
        "        if name in self._WRITES:",
        "            self.db.tick += 1",
        "        return out",
        "",
    ]
    # one @is_tool method per ToolSpec
    for name, ts in spec.tools.items():
        kind = "READ" if ts.kind == "read" else "WRITE"
        sig, args = _tool_param_lines(spec, name)
        doc = (ts.desc or name).replace("\n", " ")
        lines += [
            f"    @is_tool(ToolType.{kind})",
            f"    def {name}(self{sig and ', ' + sig}):",
            f'        """{doc}',
            "",
            "        Returns:",
            "            The tool result.",
            '        """',
            f"        return self._run({json.dumps(name)}, {{{args}}})",
            "",
        ]
    # assertion tools: one per archetype, running the spec's own goal fn
    for arch in spec.archetypes:
        lines += [
            "    @is_tool(ToolType.READ)",
            f"    def assert_{arch}_ok(self) -> bool:",
            '        """Spec-derived assertion (mirror of the goal fn)."""',
            "        view = _View(self.db)",
            f'        ok, _ = _goal_{arch}(view, view.get("_ctx"))',
            "        return ok",
            "",
        ]
    return "\n".join(lines)


def _gen_environment(spec: DomainSpec) -> str:
    cap = spec.name.replace("_", " ").title().replace(" ", "")
    up = spec.name.upper()
    lines = [
        f'"""{cap} environment. GENERATED by BenchBrew (do not edit)."""',
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "from typing import Optional",
        "",
        "from tau2.environment.environment import Environment",
        "from tau2.data_model.tasks import Task",
        "from tau2.utils import load_file",
        "",
        f"from .data_model import {cap}DB",
        f"from .tools import {cap}Tools",
        f"from .utils import {up}_DB_PATH, {up}_POLICY_PATH, {up}_TASK_SET_PATH",
        "",
        "",
        f"def get_environment(db: Optional[{cap}DB] = None,",
        "                    solo_mode: bool = False) -> Environment:",
        '    if solo_mode:',
        f'        raise ValueError("{spec.name} domain does not support solo mode")',
        "    if db is None:",
        f"        db = {cap}DB.load({up}_DB_PATH)",
        f"    tools = {cap}Tools(db)",
        f"    with open({up}_POLICY_PATH, \"r\") as fp:",
        "        policy = fp.read()",
        f'    return Environment(domain_name="{spec.name}", policy=policy, tools=tools)',
        "",
        "",
        'def get_tasks(task_split_name: Optional[str] = "base") -> list[Task]:',
        f"    tasks = load_file({up}_TASK_SET_PATH)",
        "    tasks = [Task.model_validate(task) for task in tasks]",
        "    if task_split_name is None:",
        "        return tasks",
        "    task_splits = get_tasks_split()",
        "    if task_split_name not in task_splits:",
        "        raise ValueError(",
        '            f"Invalid task split name: {task_split_name}. '
        'Valid splits are: {task_splits.keys()}"',
        "        )",
        "    return [task for task in tasks if task.id in task_splits[task_split_name]]",
        "",
        "",
        "def get_tasks_split() -> dict[str, list[str]]:",
        "    split_file = (",
        f"        Path({up}_TASK_SET_PATH).parent",
        f"        / f\"split_{{Path({up}_TASK_SET_PATH).stem}}.json\"",
        "    )",
        "    return load_file(split_file)",
        "",
    ]
    return "\n".join(lines)


def _gen_utils(spec: DomainSpec) -> str:
    up = spec.name.upper()
    return (
        f'"""{spec.name} data paths. GENERATED by BenchBrew."""\n'
        "from pathlib import Path\n"
        "\n"
        "_DATA = Path(__file__).parent.parent.parent.parent.parent "
        f'/ "data" / "tau2" / "domains" / "{spec.name}"\n'
        f"{up}_DB_PATH = _DATA / \"db.json\"\n"
        f"{up}_POLICY_PATH = _DATA / \"policy.md\"\n"
        f"{up}_TASK_SET_PATH = _DATA / \"tasks.json\"\n"
    )


def _policy_md(spec: DomainSpec) -> str:
    plat = getattr(spec, "platform", None) or {}
    lines = [
        f"# {plat.get('name', spec.name)} policy",
        "",
        f"Policy snapshot: {spec.version} ({plat.get('snapshot', '?')}). "
        "Every rule traces to a real-world source (BenchBrew GROUNDING.md).",
        "",
        "## Platform profile",
        f"Mediation: {plat.get('mediation', 'see GROUNDING.md')}.",
    ]
    if plat.get("fee") is not None:
        lines.append(f"Fees: {plat['fee']}.")
    lines += [
        "",
        "## Rules (the oracle)",
    ]
    for name, src in spec.rule_sources.items():
        lines.append(f"- **{name}**: {src}")
    pats = plat.get("scam_patterns") or {}
    if pats:
        lines += ["", "## Scam patterns (the tell is in the text)"]
        for p in pats.values():
            lines.append(f"- {p[:100]}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------


def emit_tau2_domain(spec: DomainSpec, seed: int, tasks: list[dict],
                     world: World, tau2_root: str | Path,
                     bundle_world: dict | None = None) -> Path:
    """Emit a complete runnable τ² domain package under tau2_root.

    Returns the domain package dir (src/tau2/domains/<name>).
    """
    root = Path(tau2_root)
    src_dir = root / "src" / "tau2" / "domains" / spec.name
    data_dir = root / "data" / "tau2" / "domains" / spec.name
    src_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    # 1. embedded spec + adapter files
    (src_dir / "compat.py").write_text(_COMPAT_TEMPLATE)
    (src_dir / "spec_code.py").write_text(_spec_source(spec))
    (src_dir / "data_model.py").write_text(_gen_data_model(spec))
    (src_dir / "tools.py").write_text(_gen_tools(spec))
    (src_dir / "environment.py").write_text(_gen_environment(spec))
    (src_dir / "utils.py").write_text(_gen_utils(spec))
    (src_dir / "__init__.py").write_text("")

    # 2. db.json — the baseline world (all declared collections present)
    def _complete(collections: dict) -> dict:
        for name in spec.entities:
            collections.setdefault(name, {})
        return collections

    (data_dir / "db.json").write_text(
        json.dumps(_complete(json.loads(world.canonical())["collections"]),
                   indent=2, default=str)
    )

    # 3. tasks.json — per-task initial_state (world + promoted ctx)
    out_tasks = []
    for t in tasks:
        promoted = json.loads(t["initial_world"].canonical())
        promoted["task_ctx"] = t["ctx"]
        env_assertions = [{
            "env_type": "assistant",  # ToolRequestor = user | assistant
            "func_name": f"assert_{t['archetype']}_ok",
            "arguments": {},
            "assert_value": True,
            "message": f"task {t['id']}: {t['goal_desc'](t['ctx'])}",
        }]
        out_tasks.append({
            "id": t["id"],
            "description": {
                "purpose": f"[{t['archetype']}] {t['goal_desc'](t['ctx'])}",
                "relevant_policies": None,
                "notes": f"role={t['role']}",
            },
            "user_scenario": {
                "persona": None,
                "instructions": {
                    "task_instructions": t["prompt"],
                    "domain": spec.name,
                    "reason_for_call": "Alex needs your help.",
                    "known_info": "See initial state.",
                    "unknown_info": None,
                },
            },
            "initial_state": {
                "initialization_data": {
                    "agent_data": _complete(promoted)},
                "initialization_actions": None,
                "message_history": None,
            },
            "evaluation_criteria": {
                "actions": [],
                "communicate_info": [],
                "env_assertions": env_assertions,
                "nl_assertions": [],
                "reward_basis": ["ENV_ASSERTION"],
            },
            "annotations": {"benchbrew_ctx": t["ctx"],
                            "benchbrew_seed": seed},
        })
    (data_dir / "tasks.json").write_text(json.dumps(out_tasks, indent=2, default=str))

    # 4. split_tasks.json — base split
    (data_dir / "split_tasks.json").write_text(
        json.dumps({"base": [t["id"] for t in tasks]}, indent=2)
    )

    # 5. policy.md
    (data_dir / "policy.md").write_text(_policy_md(spec))

    # 6. register in tau2's registry (idempotent) so the CLI can resolve it
    _register_domain(root, spec.name)

    return src_dir


def _register_domain(root: Path, domain: str) -> None:
    reg = root / "src" / "tau2" / "registry.py"
    if not reg.exists():
        return
    text = reg.read_text()
    marker = f'register_domain(_bb_{domain}_get_environment, "{domain}")'
    if marker in text:
        return
    text += (
        f"\n\n# BenchBrew-generated domain: {domain} (do not edit; the emitter re-adds this)\n"
        f"from tau2.domains.{domain}.environment import (\n"
        f"    get_environment as _bb_{domain}_get_environment,\n"
        f"    get_tasks as _bb_{domain}_get_tasks,\n"
        f"    get_tasks_split as _bb_{domain}_get_tasks_split,\n"
        f")\n"
        f"registry.register_domain(_bb_{domain}_get_environment, \"{domain}\")\n"
        f"registry.register_tasks(_bb_{domain}_get_tasks, \"{domain}\", "
        f"get_task_splits=_bb_{domain}_get_tasks_split)\n"
    )
    reg.write_text(text)
